# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-alpha.3
kind: Project
metadata:
  id: slack-demo
description: it slacks us the slacks or it gets the slack again
spec:
  eventSubscriptions:
  - source: slack
    types:
      - slash_command
      - message_action
      - shortcut
  workerTemplate:
    logLevel: DEBUG
    git:
      cloneURL: https://github.com/itowlson/brigade-event-handlers.git
      ref: main
